# Generated by Django 4.2.7 on 2024-03-23 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('login', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last_name')),
                ('gender', models.CharField(blank=True, choices=[('f', 'Женский'), ('m', 'Мужской'), ('n', 'Не указан')], default='n', max_length=1)),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='photo')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='biography')),
                ('rating', models.FloatField(blank=True, default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='registration')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('birthdate_year', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1900)], verbose_name='date_of_birth')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
