# Generated by Django 4.0 on 2024-03-18 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last_name')),
                ('avatar_url', models.URLField(blank=True, verbose_name='photo')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='registration')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='biography')),
                ('birthdate_year', models.IntegerField(blank=True, default=1900, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1900)], verbose_name='year_of_birth')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
