# Generated by Django 4.0 on 2024-03-18 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last_email')),
                ('avatar_url', models.URLField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('birthdate_year', models.IntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1900)], verbose_name='year_of_birth')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
